/* 
 * KvalCAM API
 *
 * KvalCAM interactive API documentation  Additional documentation is available here: https://docs.kvalinc.com/display/CAM/API  Examples are available on github here: https://github.com/kvalinc/KvalCAMAPIExamples
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Response to door job create request
    /// </summary>
    [DataContract]
    public partial class CreateDoorJobResponse :  IEquatable<CreateDoorJobResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDoorJobResponse" /> class.
        /// </summary>
        /// <param name="IdCreated">The newly generated id used to insert the door job.</param>
        public CreateDoorJobResponse(Guid? IdCreated = default(Guid?))
        {
            this.IdCreated = IdCreated;
        }
        
        /// <summary>
        /// The newly generated id used to insert the door job
        /// </summary>
        /// <value>The newly generated id used to insert the door job</value>
        [DataMember(Name="IdCreated", EmitDefaultValue=false)]
        public Guid? IdCreated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateDoorJobResponse {\n");
            sb.Append("  IdCreated: ").Append(IdCreated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateDoorJobResponse);
        }

        /// <summary>
        /// Returns true if CreateDoorJobResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateDoorJobResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateDoorJobResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IdCreated == input.IdCreated ||
                    (this.IdCreated != null &&
                    this.IdCreated.Equals(input.IdCreated))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdCreated != null)
                    hashCode = hashCode * 59 + this.IdCreated.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
