/* 
 * KvalCAM API
 *
 * KvalCAM interactive API documentation  Additional documentation is available here: https://docs.kvalinc.com/display/CAM/API  Examples are available on github here: https://github.com/kvalinc/KvalCAMAPIExamples
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Base error type that all errors inherit from
    /// </summary>
    [DataContract]
    public partial class ErrorBase :  IEquatable<ErrorBase>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorBase" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ErrorBase() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorBase" /> class.
        /// </summary>
        /// <param name="Message">Message describing the error, this field is always present (required).</param>
        /// <param name="GenericSchemaError">Generic schema error that holds all common/generic errors that occured due to schema provided, e.g. expected a string rather than a number,   this field may be missing if no generic schema errors occured.</param>
        public ErrorBase(string Message = default(string), GenericSchemaError GenericSchemaError = default(GenericSchemaError))
        {
            // to ensure "Message" is required (not null)
            if (Message == null)
            {
                throw new InvalidDataException("Message is a required property for ErrorBase and cannot be null");
            }
            else
            {
                this.Message = Message;
            }
            this.GenericSchemaError = GenericSchemaError;
        }
        
        /// <summary>
        /// Message describing the error, this field is always present
        /// </summary>
        /// <value>Message describing the error, this field is always present</value>
        [DataMember(Name="Message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Generic schema error that holds all common/generic errors that occured due to schema provided, e.g. expected a string rather than a number,   this field may be missing if no generic schema errors occured
        /// </summary>
        /// <value>Generic schema error that holds all common/generic errors that occured due to schema provided, e.g. expected a string rather than a number,   this field may be missing if no generic schema errors occured</value>
        [DataMember(Name="GenericSchemaError", EmitDefaultValue=false)]
        public GenericSchemaError GenericSchemaError { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ErrorBase {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  GenericSchemaError: ").Append(GenericSchemaError).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ErrorBase);
        }

        /// <summary>
        /// Returns true if ErrorBase instances are equal
        /// </summary>
        /// <param name="input">Instance of ErrorBase to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ErrorBase input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.GenericSchemaError == input.GenericSchemaError ||
                    (this.GenericSchemaError != null &&
                    this.GenericSchemaError.Equals(input.GenericSchemaError))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.GenericSchemaError != null)
                    hashCode = hashCode * 59 + this.GenericSchemaError.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
