/* 
 * KvalCAM API
 *
 * KvalCAM interactive API documentation  Additional documentation is available here: https://docs.kvalinc.com/display/CAM/API  Examples are available on github here: https://github.com/kvalinc/KvalCAMAPIExamples
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The hinge feature type, a rectangle shape positioned along the T-axis by a backset, optionally includes predrill holes
    /// </summary>
    [DataContract]
    public partial class Hinge : AbstractFeature,  IEquatable<Hinge>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Hinge" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Hinge() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Hinge" /> class.
        /// </summary>
        /// <param name="Bevel">Bevel value in degrees for the hinge.</param>
        /// <param name="Length">Length of the hinge (along L-axis if on the hinge or lock door side, W-axis if on the top or bottom door side).</param>
        /// <param name="Backset">Backset of the hinge (uncut space between hinge rectangle and face edge of door that is referenced along T-axis).</param>
        /// <param name="Depth">Depth of the hinge.</param>
        /// <param name="Radius1">Corner radius closest to length dimension reference (L-axis reference if on the hinge or lock door side, W-axis reference if on the top or bottom door side).</param>
        /// <param name="Radius2">Corner radius furthest from length dimension reference (L-axis reference if on the hinge or lock door side, W-axis reference if on the top or bottom door side).</param>
        /// <param name="IsPredrillOn">Toggle for predrill on/off.</param>
        /// <param name="PredrillDiameter">Diameter of the predrill holes.</param>
        /// <param name="PredrillDepth">Depth of the predrill holes.</param>
        /// <param name="PredrillLocations">Location of predrill holes as X-Y offsets from the midpoint of the hinge entry edge.</param>
        public Hinge(string Bevel = default(string), string Length = default(string), string Backset = default(string), string Depth = default(string), string Radius1 = default(string), string Radius2 = default(string), bool? IsPredrillOn = default(bool?), string PredrillDiameter = default(string), string PredrillDepth = default(string), List<Point> PredrillLocations = default(List<Point>), string Name = default(string), string Description = default(string), string TLocation = default(string), string WLocation = default(string), string LLocation = default(string), DoorSideEnum? DoorSide = default(DoorSideEnum?), List<AbstractFeature> Children = default(List<AbstractFeature>), string Type = "Circle") : base(Name, Description, TLocation, WLocation, LLocation, DoorSide, Children, Type)
        {
            this.Bevel = Bevel;
            this.Length = Length;
            this.Backset = Backset;
            this.Depth = Depth;
            this.Radius1 = Radius1;
            this.Radius2 = Radius2;
            this.IsPredrillOn = IsPredrillOn;
            this.PredrillDiameter = PredrillDiameter;
            this.PredrillDepth = PredrillDepth;
            this.PredrillLocations = PredrillLocations;
        }
        
        /// <summary>
        /// Bevel value in degrees for the hinge
        /// </summary>
        /// <value>Bevel value in degrees for the hinge</value>
        [DataMember(Name="Bevel", EmitDefaultValue=false)]
        public string Bevel { get; set; }

        /// <summary>
        /// Length of the hinge (along L-axis if on the hinge or lock door side, W-axis if on the top or bottom door side)
        /// </summary>
        /// <value>Length of the hinge (along L-axis if on the hinge or lock door side, W-axis if on the top or bottom door side)</value>
        [DataMember(Name="Length", EmitDefaultValue=false)]
        public string Length { get; set; }

        /// <summary>
        /// Backset of the hinge (uncut space between hinge rectangle and face edge of door that is referenced along T-axis)
        /// </summary>
        /// <value>Backset of the hinge (uncut space between hinge rectangle and face edge of door that is referenced along T-axis)</value>
        [DataMember(Name="Backset", EmitDefaultValue=false)]
        public string Backset { get; set; }

        /// <summary>
        /// Depth of the hinge
        /// </summary>
        /// <value>Depth of the hinge</value>
        [DataMember(Name="Depth", EmitDefaultValue=false)]
        public string Depth { get; set; }

        /// <summary>
        /// Corner radius closest to length dimension reference (L-axis reference if on the hinge or lock door side, W-axis reference if on the top or bottom door side)
        /// </summary>
        /// <value>Corner radius closest to length dimension reference (L-axis reference if on the hinge or lock door side, W-axis reference if on the top or bottom door side)</value>
        [DataMember(Name="Radius1", EmitDefaultValue=false)]
        public string Radius1 { get; set; }

        /// <summary>
        /// Corner radius furthest from length dimension reference (L-axis reference if on the hinge or lock door side, W-axis reference if on the top or bottom door side)
        /// </summary>
        /// <value>Corner radius furthest from length dimension reference (L-axis reference if on the hinge or lock door side, W-axis reference if on the top or bottom door side)</value>
        [DataMember(Name="Radius2", EmitDefaultValue=false)]
        public string Radius2 { get; set; }

        /// <summary>
        /// Toggle for predrill on/off
        /// </summary>
        /// <value>Toggle for predrill on/off</value>
        [DataMember(Name="IsPredrillOn", EmitDefaultValue=false)]
        public bool? IsPredrillOn { get; set; }

        /// <summary>
        /// Diameter of the predrill holes
        /// </summary>
        /// <value>Diameter of the predrill holes</value>
        [DataMember(Name="PredrillDiameter", EmitDefaultValue=false)]
        public string PredrillDiameter { get; set; }

        /// <summary>
        /// Depth of the predrill holes
        /// </summary>
        /// <value>Depth of the predrill holes</value>
        [DataMember(Name="PredrillDepth", EmitDefaultValue=false)]
        public string PredrillDepth { get; set; }

        /// <summary>
        /// Location of predrill holes as X-Y offsets from the midpoint of the hinge entry edge
        /// </summary>
        /// <value>Location of predrill holes as X-Y offsets from the midpoint of the hinge entry edge</value>
        [DataMember(Name="PredrillLocations", EmitDefaultValue=false)]
        public List<Point> PredrillLocations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Hinge {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Bevel: ").Append(Bevel).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Backset: ").Append(Backset).Append("\n");
            sb.Append("  Depth: ").Append(Depth).Append("\n");
            sb.Append("  Radius1: ").Append(Radius1).Append("\n");
            sb.Append("  Radius2: ").Append(Radius2).Append("\n");
            sb.Append("  IsPredrillOn: ").Append(IsPredrillOn).Append("\n");
            sb.Append("  PredrillDiameter: ").Append(PredrillDiameter).Append("\n");
            sb.Append("  PredrillDepth: ").Append(PredrillDepth).Append("\n");
            sb.Append("  PredrillLocations: ").Append(PredrillLocations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Hinge);
        }

        /// <summary>
        /// Returns true if Hinge instances are equal
        /// </summary>
        /// <param name="input">Instance of Hinge to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Hinge input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Bevel == input.Bevel ||
                    (this.Bevel != null &&
                    this.Bevel.Equals(input.Bevel))
                ) && base.Equals(input) && 
                (
                    this.Length == input.Length ||
                    (this.Length != null &&
                    this.Length.Equals(input.Length))
                ) && base.Equals(input) && 
                (
                    this.Backset == input.Backset ||
                    (this.Backset != null &&
                    this.Backset.Equals(input.Backset))
                ) && base.Equals(input) && 
                (
                    this.Depth == input.Depth ||
                    (this.Depth != null &&
                    this.Depth.Equals(input.Depth))
                ) && base.Equals(input) && 
                (
                    this.Radius1 == input.Radius1 ||
                    (this.Radius1 != null &&
                    this.Radius1.Equals(input.Radius1))
                ) && base.Equals(input) && 
                (
                    this.Radius2 == input.Radius2 ||
                    (this.Radius2 != null &&
                    this.Radius2.Equals(input.Radius2))
                ) && base.Equals(input) && 
                (
                    this.IsPredrillOn == input.IsPredrillOn ||
                    (this.IsPredrillOn != null &&
                    this.IsPredrillOn.Equals(input.IsPredrillOn))
                ) && base.Equals(input) && 
                (
                    this.PredrillDiameter == input.PredrillDiameter ||
                    (this.PredrillDiameter != null &&
                    this.PredrillDiameter.Equals(input.PredrillDiameter))
                ) && base.Equals(input) && 
                (
                    this.PredrillDepth == input.PredrillDepth ||
                    (this.PredrillDepth != null &&
                    this.PredrillDepth.Equals(input.PredrillDepth))
                ) && base.Equals(input) && 
                (
                    this.PredrillLocations == input.PredrillLocations ||
                    this.PredrillLocations != null &&
                    this.PredrillLocations.SequenceEqual(input.PredrillLocations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Bevel != null)
                    hashCode = hashCode * 59 + this.Bevel.GetHashCode();
                if (this.Length != null)
                    hashCode = hashCode * 59 + this.Length.GetHashCode();
                if (this.Backset != null)
                    hashCode = hashCode * 59 + this.Backset.GetHashCode();
                if (this.Depth != null)
                    hashCode = hashCode * 59 + this.Depth.GetHashCode();
                if (this.Radius1 != null)
                    hashCode = hashCode * 59 + this.Radius1.GetHashCode();
                if (this.Radius2 != null)
                    hashCode = hashCode * 59 + this.Radius2.GetHashCode();
                if (this.IsPredrillOn != null)
                    hashCode = hashCode * 59 + this.IsPredrillOn.GetHashCode();
                if (this.PredrillDiameter != null)
                    hashCode = hashCode * 59 + this.PredrillDiameter.GetHashCode();
                if (this.PredrillDepth != null)
                    hashCode = hashCode * 59 + this.PredrillDepth.GetHashCode();
                if (this.PredrillLocations != null)
                    hashCode = hashCode * 59 + this.PredrillLocations.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
