/* 
 * KvalCAM API
 *
 * KvalCAM interactive API documentation  Additional documentation is available here: https://docs.kvalinc.com/display/CAM/API  Examples are available on github here: https://github.com/kvalinc/KvalCAMAPIExamples
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// LWTLocation
    /// </summary>
    [DataContract]
    public partial class LWTLocation :  IEquatable<LWTLocation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LWTLocation" /> class.
        /// </summary>
        /// <param name="TLocation">Distance from the feature group TDoorReference reference along the T-axis for all features in this feature group to anchor from, must be a real number.</param>
        /// <param name="WLocation">Distance from the feature group WDoorReference reference along the W-axis for all features in this feature group to anchor from, must be a real number.</param>
        /// <param name="LLocation">Distance from the feature group LDoorReference reference along the L-axis for all features in this feature group to anchor from, must be a real number.</param>
        public LWTLocation(string TLocation = default(string), string WLocation = default(string), string LLocation = default(string))
        {
            this.TLocation = TLocation;
            this.WLocation = WLocation;
            this.LLocation = LLocation;
        }
        
        /// <summary>
        /// Distance from the feature group TDoorReference reference along the T-axis for all features in this feature group to anchor from, must be a real number
        /// </summary>
        /// <value>Distance from the feature group TDoorReference reference along the T-axis for all features in this feature group to anchor from, must be a real number</value>
        [DataMember(Name="TLocation", EmitDefaultValue=false)]
        public string TLocation { get; set; }

        /// <summary>
        /// Distance from the feature group WDoorReference reference along the W-axis for all features in this feature group to anchor from, must be a real number
        /// </summary>
        /// <value>Distance from the feature group WDoorReference reference along the W-axis for all features in this feature group to anchor from, must be a real number</value>
        [DataMember(Name="WLocation", EmitDefaultValue=false)]
        public string WLocation { get; set; }

        /// <summary>
        /// Distance from the feature group LDoorReference reference along the L-axis for all features in this feature group to anchor from, must be a real number
        /// </summary>
        /// <value>Distance from the feature group LDoorReference reference along the L-axis for all features in this feature group to anchor from, must be a real number</value>
        [DataMember(Name="LLocation", EmitDefaultValue=false)]
        public string LLocation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LWTLocation {\n");
            sb.Append("  TLocation: ").Append(TLocation).Append("\n");
            sb.Append("  WLocation: ").Append(WLocation).Append("\n");
            sb.Append("  LLocation: ").Append(LLocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LWTLocation);
        }

        /// <summary>
        /// Returns true if LWTLocation instances are equal
        /// </summary>
        /// <param name="input">Instance of LWTLocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LWTLocation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TLocation == input.TLocation ||
                    (this.TLocation != null &&
                    this.TLocation.Equals(input.TLocation))
                ) && 
                (
                    this.WLocation == input.WLocation ||
                    (this.WLocation != null &&
                    this.WLocation.Equals(input.WLocation))
                ) && 
                (
                    this.LLocation == input.LLocation ||
                    (this.LLocation != null &&
                    this.LLocation.Equals(input.LLocation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TLocation != null)
                    hashCode = hashCode * 59 + this.TLocation.GetHashCode();
                if (this.WLocation != null)
                    hashCode = hashCode * 59 + this.WLocation.GetHashCode();
                if (this.LLocation != null)
                    hashCode = hashCode * 59 + this.LLocation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
