/* 
 * KvalCAM API
 *
 * KvalCAM interactive API documentation  Additional documentation is available here: https://docs.kvalinc.com/display/CAM/API  Examples are available on github here: https://github.com/kvalinc/KvalCAMAPIExamples
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Parameters used to send a command request to a particular machine in a machine line
    /// </summary>
    [DataContract]
    public partial class MachinesCommandParameters :  IEquatable<MachinesCommandParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MachinesCommandParameters" /> class.
        /// </summary>
        /// <param name="MachineName">Unique name of the machine the command is targeting (matches MachineName in /GET machines).</param>
        /// <param name="Command">Name of the command.</param>
        /// <param name="CommandParameters">Parameters for the command if any, ignored if no parameters are needed for the command.</param>
        public MachinesCommandParameters(string MachineName = default(string), string Command = default(string), Object CommandParameters = default(Object))
        {
            this.MachineName = MachineName;
            this.Command = Command;
            this.CommandParameters = CommandParameters;
        }
        
        /// <summary>
        /// Unique name of the machine the command is targeting (matches MachineName in /GET machines)
        /// </summary>
        /// <value>Unique name of the machine the command is targeting (matches MachineName in /GET machines)</value>
        [DataMember(Name="MachineName", EmitDefaultValue=false)]
        public string MachineName { get; set; }

        /// <summary>
        /// Name of the command
        /// </summary>
        /// <value>Name of the command</value>
        [DataMember(Name="Command", EmitDefaultValue=false)]
        public string Command { get; set; }

        /// <summary>
        /// Parameters for the command if any, ignored if no parameters are needed for the command
        /// </summary>
        /// <value>Parameters for the command if any, ignored if no parameters are needed for the command</value>
        [DataMember(Name="CommandParameters", EmitDefaultValue=false)]
        public Object CommandParameters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MachinesCommandParameters {\n");
            sb.Append("  MachineName: ").Append(MachineName).Append("\n");
            sb.Append("  Command: ").Append(Command).Append("\n");
            sb.Append("  CommandParameters: ").Append(CommandParameters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MachinesCommandParameters);
        }

        /// <summary>
        /// Returns true if MachinesCommandParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of MachinesCommandParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MachinesCommandParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MachineName == input.MachineName ||
                    (this.MachineName != null &&
                    this.MachineName.Equals(input.MachineName))
                ) && 
                (
                    this.Command == input.Command ||
                    (this.Command != null &&
                    this.Command.Equals(input.Command))
                ) && 
                (
                    this.CommandParameters == input.CommandParameters ||
                    (this.CommandParameters != null &&
                    this.CommandParameters.Equals(input.CommandParameters))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MachineName != null)
                    hashCode = hashCode * 59 + this.MachineName.GetHashCode();
                if (this.Command != null)
                    hashCode = hashCode * 59 + this.Command.GetHashCode();
                if (this.CommandParameters != null)
                    hashCode = hashCode * 59 + this.CommandParameters.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
