/* 
 * KvalCAM API
 *
 * KvalCAM interactive API documentation  Additional documentation is available here: https://docs.kvalinc.com/display/CAM/API  Examples are available on github here: https://github.com/kvalinc/KvalCAMAPIExamples
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Parameters for inserting or updating a door job
    /// </summary>
    [DataContract]
    public partial class UpsertDoorJobParameters :  IEquatable<UpsertDoorJobParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpsertDoorJobParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpsertDoorJobParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpsertDoorJobParameters" /> class.
        /// </summary>
        /// <param name="DoorJob">Door job data used to insert or update a feature group, id in door job is used (required).</param>
        public UpsertDoorJobParameters(DoorJob DoorJob = default(DoorJob))
        {
            // to ensure "DoorJob" is required (not null)
            if (DoorJob == null)
            {
                throw new InvalidDataException("DoorJob is a required property for UpsertDoorJobParameters and cannot be null");
            }
            else
            {
                this.DoorJob = DoorJob;
            }
        }
        
        /// <summary>
        /// Door job data used to insert or update a feature group, id in door job is used
        /// </summary>
        /// <value>Door job data used to insert or update a feature group, id in door job is used</value>
        [DataMember(Name="DoorJob", EmitDefaultValue=false)]
        public DoorJob DoorJob { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpsertDoorJobParameters {\n");
            sb.Append("  DoorJob: ").Append(DoorJob).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpsertDoorJobParameters);
        }

        /// <summary>
        /// Returns true if UpsertDoorJobParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of UpsertDoorJobParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpsertDoorJobParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DoorJob == input.DoorJob ||
                    (this.DoorJob != null &&
                    this.DoorJob.Equals(input.DoorJob))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DoorJob != null)
                    hashCode = hashCode * 59 + this.DoorJob.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
